dist: trusty
language: node_js
node_js:
  - "6"
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database hackathonictest;' -U postgres
script:
  - npm start &
  - sleep 5; npm test
